export const FETCH_MOVIES = 'FETCH_MOVIES';
export const SEARCH_MOVIES = 'SEARCH_MOVIES';
export const APPLY_MOVIES = 'APPLY_MOVIES';

export const FETCH_CURRENT_MOVIE = 'FETCH_CURRENT_MOVIE';
export const APPLY_CURRENT_MOVIE = 'APPLY_CURRENT_MOVIE';

export const SORT_MOVIES = 'SORT_MOVIES';

export const BACK_TO_SEARCH = 'BACK_TO_SEARCH';

export const NO_PATH = 'NO_PATH';
